version: "3.9"
networks:
  web:
    external: true
  ainetwork:
    external: false

services:
  abnkhojdatabase:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - khoj_db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ainetwork

  abnkhoj:
    depends_on:
      abnkhojdatabase:
        condition: service_healthy
    # Use the following line to use the latest version of khoj. Otherwise, it will build from source.
    # image: ghcr.io/khoj-ai/khoj:latest
    # Uncomment the following line to build from source. This will take a few minutes. Comment the next two lines out if you want to use the offiicial image.
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      # If changing the local port (left hand side), no other changes required.
      # If changing the remote port (right hand side),
      #   change the port in the args in the build section,
      #   as well as the port in the command section to match
      - "42110:42110"
    working_dir: /app
    volumes:
      - khoj_config:/root/.khoj/
      - khoj_models:/root/.cache/torch/sentence_transformers
    # Use 0.0.0.0 to explicitly set the host ip for the service on the container. https://pythonspeed.com/articles/docker-connection-refused/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=abnkhojdatabase
      - POSTGRES_PORT=5432
      - KHOJ_DJANGO_SECRET_KEY=secret
      - KHOJ_DEBUG=False
      - KHOJ_ADMIN_EMAIL=username@example.com
      - KHOJ_ADMIN_PASSWORD=password
      # Uncomment the following lines to make your instance publicly accessible. Replace the domain with your domain. Proceed with caution, especially if you are using anonymous mode.
      # - KHOJ_NO_HTTPS=True
      - KHOJ_DOMAIN=chat.abnasia.org
    labels:
      - traefik.http.routers.abnkhoj.rule=Host(`chat.abnasia.org`)
      - traefik.http.routers.abnkhoj.tls=true
      - traefik.http.routers.abnkhoj.tls.certresolver=lets-encrypt
    networks:
      - web
      - ainetwork

    command: --host="0.0.0.0" --port=42110 -vv --anonymous-mode


volumes:
  khoj_config:
  khoj_db:
  khoj_models:
